### PR TITLE
Cody/Oauth-loading-states

### LINKED ISSUE #47: [Authentication] Add loading states to Google OAuth flow
Add loading states to Google OAuth flow

**Must have:**
- [x] Loading spinner on login button while authenticating
- [ ] Loading screen during Google redirect
- [x] Loading state when checking auth status
- [x] Error messages for failed auth
- [x] Auto-redirect to dashboard if logged in
- [x] Auto-redirect to home if not logged in

### PR DESCRIPTION
**Pull request by kepsteen**
Closes #47 

One thing to note: I created a spinner with an animating path using framer-motion, but I could not figure out how to use it in the loading.tsx files to create a global loading page. I spent quite a bit of time on this, but eventually, I gave up 😔. I left the component in case I or someone else wants to try to figure it out.

- moved Login page to `/auth/login`
  - this way we can add a landing page if we have time
- added loading and error states for the Google Oauth flow
- updated middleware to redirect unauthenticated users to the login page
## Error state
Recording 2024-12-18 at 15 30 18
## Loading State of Login Button
Recording 2024-12-18 at 15 41 33
## Redirect Unauthenticated Users to Login
Recording 2024-12-18 at 15 43 33

### CODE REVIEW

File: lib/supabase/middleware.ts [hunk 1]
```diff
@@ -66,6 +70,14 @@ export async function updateSession(request: NextRequest) {
...
 			url.pathname = "/onboarding";
 			return NextResponse.redirect(url);
+		} else if (
+			profile &&
+			profile.onboarding_complete &&
+			request.nextUrl.pathname.startsWith("/onboarding")
+		) {
+			const url = request.nextUrl.clone();
+			url.pathname = "/dashboard";
+			return NextResponse.redirect(url);
```
Comment (thomasnguyen) [inline lib/supabase/middleware.ts:80]: hmm just thinking aloud. We might want to allow users to go back to the onboarding flow, just in case they want to update their profile. 

If they did though, we need to fetch the existing data and populate the fields.

File: components/LoginButton/LoginButton.tsx [hunk 2]
```diff
@@ -1,9 +1,16 @@
...
+import { LoadingSpinner } from "../LoadingSpinner/LoadingSpinner";
+import { redirect } from "next/navigation";
 
 export default function LoginButton({ redirectPath = "/onboarding" }) {
+	const [isLoading, setIsLoading] = useState(false);
+
 	const signInWithGoogle = async () => {
+		setIsLoading(true);
 		const supabase = createClient();
 		const { error } = await supabase.auth.signInWithOAuth({
```
Comment (thomasnguyen) [inline components/LoginButton/LoginButton.tsx:15]: Just thinking aloud again, but I think we should check if the user has completed their profile and then redirect them to either onboarding or dashboard depending if they are new vs old user.

Not really related to this PR but am thinking aloud.

File: app/auth/error/page.tsx [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+			<h1 className="text-4xl text-white text-center mb-4">
+				Authentication Error
+			</h1>
+			<p className="text-white text-center">
+				There was a problem signing in with Google. Please try again or contact
+				support if the issue persists.
+			</p>
+		</main>
+	);
+}
```
Comment (thomasnguyen) [inline app/auth/error/page.tsx:13]: 🙏

**Review by thomasnguyen — APPROVED** [review]
Appreciate the work and also the video screenshots.

have some questions but they are non blocking
