### PR TITLE
fix #650: Fix GiftExchangePage crashes w/ non-group user and status is not pending

### LINKED ISSUE #650: Gift Exchange page issue that crashes
When a non-user/non-member tries to navigate to a gift exchange page AFTER it has already been drawn, the app crashes.

Image

### PR DESCRIPTION
**Pull request by tonyb650**
### Before: 
When a user, whether logged in or not, tries to navigate to a gift exchange page **after** the drawing has occurred (`status` is no longer 'pending'), the app crashes.

This occurred because the page should not be rendered at all if the group has already held it's drawing and the user is not part of that group.

### After: 
As part of the data fetching function that is fired by the page's `useEffect`, the following checks and new behaviors have been added:
1) If the `isSignedIn` status of the user has not been established yet, there is an early return before any data fetching
2) If the data fetching returns with an `error` property, the user is redirected to dashboard with a "Bad Link" toast (Case 1)
3) If the user is not logged in and the GiftExchange is no longer 'pending' (i.e.: the Drawing has already occurred), then the `signInWithGoogle` function is called (Case 2)
4) If the user is logged in but not a member of a Gift exchange that is no longer 'pending', then the user is redirect to dashboard with and "Expired Link" toast (Case 3)
5) If an error is caught during data fetching or parsing, then a "Server Error" toast is rendered.

### Additional
AuthContext was updated to make the behavior of `isSignedIn` more useful. `isSignedIn` now remains `null` until the session status can be determined and then is set to `true` or `false` once the session status is known.

 Closes #650

## Testing instructions
To test,
* Case 1: Create a user and complete onboard. Type/paste an 'invite' link with a bad `id` param into browser. This will render the "Bad Link" toast.
* Create a group or update a group and copy and save the 'invite' link.
* Complete the 'drawing' action. This will update the `status` to 'active'.
* Case 2. Log out. Paste in the link to the browser. This will initiate Google login.
* Case 3. Log in as a user who is not a part of the group. Paste in the link to the browser to get the 'Expired' toast.
 
## Screenshots
image

## Pre-submission checklist

- [x] Code builds and passes locally
- [x] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format (e.g. `test #001: created unit test for __ component`)
- [x] Request reviews from the `Peer Code Reviewers` and `Senior+ Code Reviewers` groups
- [x] Thread has been created in Discord and PR is linked in `gis-code-questions`

### CODE REVIEW

File: context/AuthContextProvider.tsx [hunk 1]
```diff
@@ -70,8 +70,8 @@ const AuthContextProvider: FC<{ children: ReactNode }> = ({ children }) => {
             data: { user },
           } = await supabase.auth.getUser();
           setUser(user);
-          setIsSignedIn(true);
         }
+        setIsSignedIn(!!session);
```
Comment (shashilo) [inline context/AuthContextProvider.tsx]: This is a significant change. Why was this moved outside the if statement? Also, no unit tests were updated. That's bad. Either we don't have a unit test for this yet, or there's a failing build coming soon.

File: app/gift-exchanges/[id]/page.tsx [hunk 2]
```diff
@@ -69,29 +80,60 @@ export default function GiftExchangePage() {
...
+        });
+        return;
+      }
+
+      if (isUserLoggedIn && !isExchangePending && !isUserAGroupMember) {
+        router.push('/dashboard');
+        toast({
+          variant: ToastVariants.Error,
+          title: `Expired Link`,
+          description: `Sorry, the specified link is no longer valid.`,
```
Comment (shashilo) [inline app/gift-exchanges/[id]/page.tsx]:
```suggestion
          description: `Sorry, this invitation is no longer valid.`,
```

File: app/gift-exchanges/[id]/page.tsx [hunk 3]
```diff
@@ -129,9 +171,9 @@ export default function GiftExchangePage() {
             </section>
             <section className="flex flex-col">
               <h1 className="font-bold">Gift Suggestions</h1>
-              {giftSuggestions.length === 0 && <WaitingForSuggestions />}
+              {giftSuggestions?.length === 0 && <WaitingForSuggestions />}
 
-              {giftSuggestions.length !== 0 && (
+              {giftSuggestions?.length > 0 && (
```
Comment (shashilo) [inline app/gift-exchanges/[id]/page.tsx]: What is this fixing?

File: app/gift-exchanges/[id]/page.test.tsx [hunk 4]
```diff
@@ -32,37 +24,96 @@ jest.mock('@/app/api/openaiConfig/config', () => ({
...
+    (global.fetch as jest.Mock)
+      .mockResolvedValueOnce({
+        json: async () => ({ error: 'Error' }),
+      })
+      .mockResolvedValueOnce({
+        json: async () => ({ error: 'Error' }),
+      })
+      .mockResolvedValueOnce({
+        json: async () => ({ error: 'Error' }),
+      });
```
Comment (shashilo) [inline app/gift-exchanges/[id]/page.test.tsx]: Why is there 3 copies of the same mock method?

File: app/gift-exchanges/[id]/page.test.tsx [hunk 5]
```diff
@@ -84,4 +136,67 @@ describe('GiftExchangePage Warning Modal', () => {
...
+  it('displays a Server Error toast if data fetching throws an error', async () => {
+    (useAuthContext as jest.Mock).mockReturnValue(mockMemberSession);
+    mockRejectedFetch();
+
+    render(<GiftExchangePage />);
+
+    await waitFor(() => {
+      expect(mockToast).toHaveBeenCalledWith({
+        variant: 'error',
+        title: 'Server Error',
```
Comment (shashilo) [inline app/gift-exchanges/[id]/page.test.tsx]: Instead of making these toast strings, create these strings into consts since they are not being reused.

**Review by shashilo — CHANGES_REQUESTED** [review]

File: app/gift-exchanges/[id]/page.tsx [hunk 6]
```diff
@@ -69,29 +80,60 @@ export default function GiftExchangePage() {
...
+      if (!isExchangePending && !isUserLoggedIn) {
+        await signInWithGoogle({
+          redirectPath: window.location.pathname,
+        });
+        return;
+      }
+
+      if (isUserLoggedIn && !isExchangePending && !isUserAGroupMember) {
+        router.push('/dashboard');
+        toast({
```
[the remark this answers is not in the document]
Comment (tonyb650) [reply app/gift-exchanges/[id]/page.tsx]: I don't think it matters. I tested it both ways and in my environment I couldn't discern any difference.

I'm thinking that if the ToastProvider was not global, then potentially a Toast that is rendered first would be removed with the redirect and that would mean the Toast should come after. But that's not the case here as far as I can tell

File: app/gift-exchanges/[id]/page.test.tsx (hunk 4 above)
Comment (tonyb650) [reply app/gift-exchanges/[id]/page.test.tsx]: I copied the pattern that was already in the test for the 3 successful data fetching and it seemed to work well for the 3 "error" fetch calls needed for the 'bad link' response.

File: app/gift-exchanges/[id]/page.test.tsx (hunk 5 above)
Comment (tonyb650) [reply app/gift-exchanges/[id]/page.test.tsx]: Done

File: app/gift-exchanges/[id]/page.tsx [hunk 7]
```diff
@@ -69,29 +80,60 @@ export default function GiftExchangePage() {
...
+          description: `Sorry, the specified link is no longer valid.`,
+        });
+        return;
       }
     } catch (error) {
       console.error('Error fetching data:', error);
+      toast({
+        variant: ToastVariants.Error,
+        title: `Server Error`,
+        description: `Sorry, there was a network error.`,
```
[the remark this answers is not in the document]
Comment (nickytonline) [reply app/gift-exchanges/[id]/page.tsx]: +1 to this. Always display friendly errors and log the actual errors.

File: app/gift-exchanges/[id]/page.test.tsx (hunk 4 above)
Comment (tonyb650) [reply app/gift-exchanges/[id]/page.test.tsx]: It needs to get back a response (either actual data or {error: "message"}) for all 3 fetch calls. If any of the 3 fetches are rejected then an error is thrown and we end up in the `catch` block, which isn't what we want for this execution path.   

I think a big improvement would be this:
```
const mockFetchWithoutValidData = () => {
   (global.fetch as jest.Mock)
     .mockResolvedValue({
       json: async () => ({error: "Error"}),
    })
}
```

Then all the fetch calls get the same response, regardless of how many there are.

File: app/gift-exchanges/[id]/page.test.tsx [hunk 8]
```diff
@@ -84,4 +136,67 @@ describe('GiftExchangePage Warning Modal', () => {
...
+    (useAuthContext as jest.Mock).mockReturnValue(mockNonMemberSession);
+    mockDataFetch('active');
+
+    render(<GiftExchangePage />);
+
+    await waitFor(() => {
+      expect(routerPush).toHaveBeenCalledWith('/dashboard');
+
+      expect(mockToast).toHaveBeenCalledWith({
+        variant: 'error',
```
[the remark this answers is not in the document]
Comment (shashilo) [reply app/gift-exchanges/[id]/page.test.tsx]: Yes, and the other strings as well

File: context/AuthContextProvider.tsx (hunk 1 above)
Comment (shashilo) [reply context/AuthContextProvider.tsx]: Pretty much, which scenario is this fixing? Is it causing regressions?

Comment (tonyb650) [reply context/AuthContextProvider.tsx]: Here's the scenario: The user is logged in, but when our page is first mounted, `useAuthContext` fires its useEffect and that in turn awaits `supabase.auth.getSession()`. While it is waiting, both `session` and `isSignedIn` are reverted to their default of `null`. If we are in this state and we don't exit early from `fetchGfitExchangeData`, we will enter `signInWithGoogle()` on line 107 every time.

I don't see it causing any regressions. The only place in the codebase `isSignedIn` is used is on the home page where it is compared with `true` to redirect the user to '/dashboard'. The new code should never change when it is set to `true`, only that it can now also be set to `false` in addition to `null` (when `session` is definitively not present).

File: app/gift-exchanges/[id]/page.test.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (tonyb650) [reply app/gift-exchanges/[id]/page.test.tsx]: Just realized, maybe you meant something like this:

const TOASTS = { badLink : { variant: ..., title: "Bad Link, description: "Please..."}, expiredLink: {variant: ..., title: "Expired Link", description: "..."}, ...}

Should I implement that and export it to the test file?

**Review by shashilo — APPROVED** [review]

**Review by lillian-nguyen — APPROVED** [review]
