### PR TITLE
Fix #291: fix eslint error on getAmazonImage.ts file

### LINKED ISSUE #291: Address ESlint errors in the file: ./lib/getAmazonImage.ts
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Remove file from eslint ignore
- Open terminal
- execute terminal command `npx eslint ./components/Avatar/AvatarBody.tsx`

## Existing errors:
- Line 1:1  
  - Error: missing header  header/header
- Line 1:31
  -   Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 1:53 
  -  Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type

### PR DESCRIPTION
**Pull request by Yassahr**
## Description
This PR fixes 3 eslint errors: missing JSDoc, TypeScript return type and header 

### Before: 
Running command npx eslint ./lib/getAmazonImage.ts led to the following ESLint errors:

- Line 1:1
- Error: missing header header/header
- Line 1:31
- Error: Missing JSDoc comment. jsdoc/require-jsdoc
- Line 1:53
- Error: Missing return type on function. @typescript-eslint/explicit-function-return-type

### After: 
Running command npx eslint ./lib/getAmazonImage.ts and pnpm run build led to there are no ESLint errors pertaining to  ./lib/getAmazonImage.ts file.

 Closes #291

## Testing instructions

Open repo in VSCode ( or editor of choice)
Open terminal
execute terminal command npx eslint ./lib/getAmazonImage.ts

## Additional information
N/A 

## Pre-submission checklist

- [ x] Code builds and passes locally
- [x] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format (e.g. `test #001: created unit test for __ component`)
- [x] Request reviews from the `Peer Code Reviewers` and `Senior+ Code Reviewers` groups
- [x] Thread has been created in Discord and PR is linked in `gis-code-questions`

### CODE REVIEW

**Review by suzuhe481 — APPROVED** [review]
LGTM!

File: lib/getAmazonImage.ts [hunk 1]
```diff
@@ -1,4 +1,12 @@
-export const getAmazonImage = async (title: string) => {
+// Copyright (c) Gridiron Survivor.
+// Licensed under the MIT License.
+
+/**
+ * Amazon Image
+ * @param {string} title - The title of the search item
+ * @returns {object} - The image url and response status
```
Comment (nickytonline) [inline lib/getAmazonImage.ts:7]: refactor (blocking): the function is async so even though three return value in the code looks like a plain object, it's a promise. See the function return type, `Promise<{ imageUrl: string | null, success: boolean }>`.

```suggestion
 * @returns {Promise<{ imageUrl: string | null, success: boolean }>
} - The image url and response status
```

**Review by nickytonline — APPROVED** [review]
:shipit:
