### PR TITLE
fix:#576 added cancel buttons on Create Group page

### LINKED ISSUE #519: fix: add "cancel" option for "Create Group"
Currently, there is no way for a user to exit the "Create Group" workflow other than refreshing the page or navigating to a different page. "Back to dashboard" is not clear.

Fix: add "Cancel" button to bottom of section.

### LINKED ISSUE #576: Create Secret Santa Group Dialog Should Have a Cancel button
The create group button should remain as the main call to action (CTA), but there should be a secondary Cancel CTA button.
Image

### PR DESCRIPTION
**Pull request by tonyb650**
### Before: 
Navigating away from the "Create Group" page was unintuitive, with only the "< Back to Dashboard" link and no "Cancel" button.

### After: 
There are now 2 additional, more conventional ways to navigate back to the dashboard page: an "X" button in the upper-right corner and a "Cancel" button at the bottom of the page. (See 'After' screenshot)

Closes #576
Closes #519

## Additional information
* Also added tests that the new elements render as expected with the correct `href`.
* It was necessary to update `jest.setup.js` to bypass `next/image` external src url restrictions.
* **Similar functionality is also needed on the "Edit Group" page.** There is currently no ticket for this.

### Before
Image

### After
image

## Pre-submission checklist

- [x] Code builds and passes locally
- [x] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format (e.g. `test #001: created unit test for __ component`)
- [x] Request reviews from the `Peer Code Reviewers` and `Senior+ Code Reviewers` groups
- [x] Thread has been created in Discord and PR is linked in `gis-code-questions`

### CODE REVIEW

File: app/create-group-page/page.tsx [hunk 1]
```diff
@@ -114,7 +115,14 @@ export default function CreateGroupPage() {
       </div>
       <div className="flex items-center justify-center h-full">
         <div className="bg-white w-full xl:w-1/2 mb-5 flex justify-center align-center rounded flex-col ">
-          <h2 className="font-bold m-5">Create Secret Santa Page</h2>
+          <div className="flex justify-end m-1.5">
+            <Button variant="ghost" asChild data-testid="x-button">
```
Comment (suzuhe481) [inline app/create-group-page/page.tsx]: I don't know if this X button is necessary because now there's 3 ways to get back to the dashboard, with 2 of them being close together. Maybe if this was a popup modal instead of a page, but this is still mainly a design choice. I'll wait for a senior reviewer to chime in and see what they think.

**Comment by BaconDesigns** [comment]
@tonyb650  Is there a URL to see this in staging or whichever environment this page lives correctly? Thank you.
