### PR TITLE
fix #632: Fixed crashing when no image is selected while creating group

### LINKED ISSUE #632: Dashboard crashes if theme image not selected following group creation
Creating a group without selecting a group theme image causes the dashboard to crash on page redirect. 

https://github.com/user-attachments/assets/4e9557ba-6001-4f7e-8f0c-2513dd69f071

Image
Image

### PR DESCRIPTION
**Pull request by tonyb650**
### Before: 
CreateGroup form and EditGroup form would pass validation without a valid `src` for group image. This would cause the app to crash when the `GiftCard` component attempts to render an `<Image />` with an invalid `src` string.

### After: 
Made the following changes to address this issue:
1) Added a TS interface to enforce the shape of objects in the `GROUP_IMAGES` array.
2) Added Zod validation of the `group_image` form field on the  Create Group page and the Edit Group page such that the value must be one of the `src` values from the list.
3) Added a fallback `GiftBoxArt` SVG image on `GiftExchangeHeader.tsx` and `GroupCard.tsx` the case of a falsey `src` value.

As a result, neither form can be submitted without one of the specified src urls as the `group_image`. Moreover, in case of an empty string or `null` `group_image` from existing records in the DB, a fallback will be displayed instead of a broken image icon.

 Closes #632

## Additional information
Additionally, as part of defining a `GroupImage` interface, `title` and `alt` are now split into two separate properties, since they serve unique purposes. 

## Screenshots
image

## Pre-submission checklist

- [x] Code builds and passes locally
- [x] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format (e.g. `test #001: created unit test for __ component`)
- [x] Request reviews from the `Peer Code Reviewers` and `Senior+ Code Reviewers` groups
- [x] Thread has been created in Discord and PR is linked in `gis-code-questions`

### CODE REVIEW

File: components/GroupCard/GroupCard.tsx [hunk 1]
```diff
@@ -48,7 +49,7 @@ const GroupCard = ({ giftExchange }: GroupCardProps): JSX.Element => {
       <div className="h-28 flex items-center p-4 rounded-xl bg-groupCardGreen">
         <Image
           className="h-16 w-16 lg:h-20 lg:w-20 rounded-xl"
-          src={giftExchange.group_image}
+          src={giftExchange.group_image || GiftBoxArt}
```
Comment (shashilo) [inline components/GroupCard/GroupCard.tsx]: Same here. Make the first item the default.

File: components/ImageSelector/ImageSelector.tsx [hunk 2]
```diff
@@ -58,13 +69,13 @@ export function ImageSelector({ value, onChange }: ImageSelectorProps) {
               <div className="relative aspect-video">
                 <Image
                   src={image.src}
-                  alt={image.alt}
+                  alt={image?.alt || ""}
```
Comment (shashilo) [inline components/ImageSelector/ImageSelector.tsx]: Should not need the or here.
```suggestion
                  alt={image?.alt}
```

File: components/ImageSelector/ImageSelector.tsx [hunk 3]
```diff
@@ -6,32 +6,43 @@ import { RadioGroup } from '@/components/RadioGroup/RadioGroup';
...
+  id: string
+  title: string
+  src: string
+  alt?: string
+}
+
+export const GROUP_IMAGES: GroupImage[] = [
+  {
+    id: '1',
+    title: 'Image 1',
```
Comment (shashilo) [inline components/ImageSelector/ImageSelector.tsx]: Give these images better descriptive titles.

File: components/ImageSelector/ImageSelector.tsx [hunk 4]
```diff
@@ -6,32 +6,43 @@ import { RadioGroup } from '@/components/RadioGroup/RadioGroup';
 import { RadioGroupItem } from '@/components/RadioGroup/RadioGroupItem';
 import { Label } from '@/components/Label/Label';
 
+interface GroupImage {
```
[the remark this answers is not in the document]
Comment (tonyb650) [reply components/ImageSelector/ImageSelector.tsx]: Just the new `GroupImage` interface or the interface for the component props as well? I'll just put the `GroupImage` interface there to start.

File: components/ImageSelector/ImageSelector.tsx [hunk 5]
```diff
@@ -6,32 +6,43 @@ import { RadioGroup } from '@/components/RadioGroup/RadioGroup';
...
+  src: string
+  alt?: string
+}
+
+export const GROUP_IMAGES: GroupImage[] = [
+  {
+    id: '1',
+    title: 'Image 1',
+    src: 'https://images.unsplash.com/photo-1480632563560-30f503c09195?w=6h00&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGNocmlzdG1hcyUyMGNoYXJhY3RlcnxlbnwwfHwwfHx8MA%3D%3D',
+    alt: 'Image 1',
```
[the remark this answers is not in the document]
Comment (tonyb650) [reply components/ImageSelector/ImageSelector.tsx]: Fixed.

File: app/create-group-page/page.test.tsx [hunk 6]
```diff
@@ -0,0 +1,153 @@
...
+          return Reflect.construct(OriginalDate, args, (new.target as any)) as unknown as Date;
+        } else {
+          super(mockDate.getTime());
+        }
+      }
+      
+      static now() {
+        return mockDate.getTime();
+      }
+    }) as unknown as DateConstructor;
```
Comment (nickytonline) [inline app/create-group-page/page.test.tsx]: It's not clear to me why we're mocking `Date`.

[the remark this answers is not in the document]
Comment (nickytonline) [reply app/create-group-page/page.test.tsx]: To answer your question from Slack, now that I understand you want to mock `new Date()` as well, we can use Jest timers:

in the beforeEach

```
    jest.useFakeTimers();
    jest.setSystemTime(new Date('2025-01-01T12:00:00Z'));
```

or if the new date is different in some tests, set the `jest.setSystemTime(new Date('2025-01-01T12:00:00Z'));` in that specific test.

and in the `afterEach`, just add `jest.useRealTimers();`

**Review by shashilo — APPROVED** [review]
